from fastapi.testclient import TestClient

from app.database import SessionLocal
from app.main import app
from app.models import AIChangeProposal

client = TestClient(app)


def test_get_ai_change_proposals_returns_list():
    response = client.get("/ai/change-proposals")

    assert response.status_code == 200
    assert isinstance(response.json(), list)


def test_create_ai_change_proposal_returns_new_proposal():
    created_proposal_id = None

    change_requests_response = client.get("/ai/change-requests")
    assert change_requests_response.status_code == 200

    change_requests = change_requests_response.json()
    assert len(change_requests) > 0

    change_request_id = change_requests[0]["id"]

    payload = {
        "change_request_id": change_request_id,
        "model_name": "qwen-devsecops:latest",
        "proposal_markdown": "# Test proposal\n\nGenerated by automated test.",
        "confidence_level": "High",
    }

    try:
        response = client.post("/ai/change-proposals", json=payload)

        assert response.status_code == 200

        data = response.json()
        created_proposal_id = data["id"]

        assert data["change_request_id"] == change_request_id
        assert data["model_name"] == payload["model_name"]
        assert data["proposal_markdown"] == payload["proposal_markdown"]
        assert data["confidence_level"] == "High"
        assert data["review_status"] == "PENDING_REVIEW"
        assert "created_at" in data

    finally:
        if created_proposal_id is not None:
            db = SessionLocal()
            try:
                db.query(AIChangeProposal).filter(
                    AIChangeProposal.id == created_proposal_id
                ).delete()
                db.commit()
            finally:
                db.close()
